# Generated by Django 6.0.2 on 2026-02-07 21:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_url', models.URLField(blank=True)),
                ('input_text', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('moonlight_elder', 'Moonlight Elder'), ('village_fire', 'Village Fire Storyteller'), ('wise_judge', 'Wise Judge'), ('hopeful_healer', 'Hopeful Healer'), ('playful_trickster', 'Playful Trickster')], max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('source_text', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('themes', models.JSONField(blank=True, null=True)),
                ('proverbs', models.JSONField(blank=True, null=True)),
                ('story_text', models.TextField(blank=True)),
                ('moral', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('subtitles', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
