# Generated by Django 6.0.2 on 2026-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyrequest',
            name='audio_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storyrequest',
            name='audio_format',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
